version: '3.8'

services:
  exam-dotnet-api:
    container_name: exam-dotnet-api
    build:
      context: ./exam-dotnet-8-api
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8005
    volumes:
      - ./exam-dotnet-8-api/app:/app
    depends_on:
      exam-pg-container:
        condition: service_healthy
    networks:
      - mynetwork

  angular-app:
    container_name: angular-app
    build:
      context: ./angular
      dockerfile: Dockerfile.Angular
    image: exam-angular:latest
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - exam-dotnet-api
    networks:
      - mynetwork
    volumes:
      - ./angular/exam:/app      

  exam-pg-container:
    container_name: exam_pg_container
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: examuser
      POSTGRES_PASSWORD: exampass
      POSTGRES_DB: examination
    ports:
      - "5432:5432"
    volumes:
     - ./postgres/examdata:/var/lib/postgresql/data
     - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U examuser -d examination"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork  

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@exam.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    depends_on:
      exam-pg-container:
        condition: service_healthy
    networks:
      - mynetwork

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - exam-dotnet-api
      - angular-app
    networks:
      - mynetwork


  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # MinIO API Portu
      - "9001:9001"  # MinIO Yönetim Paneli
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    networks:
      - mynetwork

networks:   
  mynetwork:
    driver: bridge
