// <auto-generated />
using System;
using BadgeService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BadgeService.Migrations
{
    [DbContext(typeof(BadgeDbContext))]
    [Migration("20251031124307_aggraget_v2")]
    partial class aggraget_v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BadgeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BadgeDefinitions");
                });

            modelBuilder.Entity("BadgeEarned", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EarnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.ToTable("BadgeEarned");
                });

            modelBuilder.Entity("StudentBadgeProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("UserId", "BadgeDefinitionId")
                        .IsUnique();

                    b.ToTable("StudentBadgeProgresses");
                });

            modelBuilder.Entity("StudentDailyActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ActivityScore")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ActivityDate")
                        .IsUnique();

                    b.ToTable("StudentDailyActivities");
                });

            modelBuilder.Entity("StudentQuestionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BestCorrectStreak")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentCorrectStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentQuestionAggregates");
                });

            modelBuilder.Entity("StudentSubjectAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectQuestions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SubjectId")
                        .IsUnique();

                    b.ToTable("StudentSubjectAggregates");
                });

            modelBuilder.Entity("BadgeEarned", b =>
                {
                    b.HasOne("BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeDefinition");
                });

            modelBuilder.Entity("StudentBadgeProgress", b =>
                {
                    b.HasOne("BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeDefinition");
                });
#pragma warning restore 612, 618
        }
    }
}
